executor: "CeleryExecutor"
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.2"
dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/astronomer/airflow_performance.git
    branch: main
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: ""
    wait: 5
    containerName: git-sync
    uid: 65533

workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

scheduler:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

env:
  - name: "AIRFLOW__CORE__PARALLELISM"
    value: "999"
  - name: "AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG"
    value: "999"
  - name: "AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG"
    value: "16"
  - name: "AIRFLOW_SLACKWEBHOOK"
    value: "T02J89GPR/B05U377436Y/xOK9xo6pxZVBbF24PqvZRWrO"

airflow:
  extraPackages:
    - apache-airflow-providers-slack
images:
  gitSync:
    repository: registry.k8s.io/git-sync/git-sync
    tag: v3.6.9
    pullPolicy: IfNotPresent