name: Install Airflow with Helm

on:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'git revision'
        required: false
        default: ''

jobs:
  install-airflow:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: "example-release"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Kind
      run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/

    - name: create kind cluster
      run: |
        kind create cluster --image kindest/node:v1.21.1


    - name: Install kubectl
      run: |
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

    - name: Install jq
      run: |
          sudo apt-get update
          sudo apt-get install -y jq

    - name: install helm
      run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh  

    - name: Add Helm repository
      run: |
            helm repo add apache-airflow https://airflow.apache.org
            helm repo update
      if: success()

    - name: Install Airflow with Helm
      working-directory: .github
      run: |
            helm install $RELEASE_NAME apache-airflow/airflow -f ./values.yaml
      if: success()

    - name: verify airflow installed
      run: | 
          kubectl get pods
          kubectl get services
          POD_NAME=($(kubectl get pods | grep -E 'worker' | awk '{print $1}'))
          echo "Pod Name: $POD_NAME"
          kubectl exec -it  $POD_NAME -- airflow version
          sleep 180s 
          kubectl exec -it  $POD_NAME -- airflow dags list
          kubectl exec -it  $POD_NAME -- airflow dags unpause init_dag
          kubectl exec -it  $POD_NAME -- airflow dags trigger init_dag -o json
          output=$(kubectl exec -it  $POD_NAME -- airflow dags trigger init_dag -o json | awk 'NR==2')  
          echo "output is : $output"
          execution_date=$(echo "$output" | jq -r '.[0].logical_date')
          echo "execution_date: $execution_date"
          # Add a loop to check the DAG state until it becomes 'success' or 'failed'
          kubectl exec -it $POD_NAME -- airflow dags state init_dag $execution_date
          while true; do
            state=$(kubectl exec -it $POD_NAME -- airflow dags state init_dag $execution_date |  awk '{print $1}')
            if [ "$state" == "success" ] || [ "$state" == "failed" ]; then
              echo "DAG state is $state."
              kubectl exec -it  $POD_NAME -- airflow tasks log -A -t run_test_task_lag_task init_dag $execution_date
              exit 1
            else
              echo "DAG state is $state. Waiting for it to become 'success' or 'failed..."
              sleep 5  # You can adjust the sleep interval as needed
            fi
          done
      if: success()

    - name: upgrade  Airflow with Helm
      working-directory: .github
      run: |
            helm upgrade $RELEASE_NAME apache-airflow/airflow -f ./values.yaml --set defaultAirflowTag=2.7.3rc1
      if: success()
